spring.application.name=SpringBootSecurityAssignment
# Optional: only needed if you want to override default users
spring.security.user.name=anand
spring.security.user.password=anand@123
server.port=9090